services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appmacro
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:7
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
